app:
    resource: '@AppBundle/Controller/'
    type: annotation

softnlabs:
    path:    /softnlabs
    defaults: {_controller: AppBundle:Softnlabs:index}

client:
    path:    /client/
    defaults: {_controller: AppBundle:Client:index}

nouveauTicket:
    path:    /nouveauTicket
    defaults: {_controller: AppBundle:NouveauTicket:index}

nouveauClient:
    path:    /nouveauClient
    defaults: {_controller: AppBundle:NouveauClient:index}

nouvelleSociete:
    path:    /nouvelleSociete
    defaults: {_controller: AppBundle:NouvelleSociete:index}

modificationSociete:
    path:    /modificationSociete
    defaults: {_controller: AppBundle:ModificationSociete:index}

softnlabs_client_part:
    path:    /softnlabsClient
    defaults: {_controller: AppBundle:SoftnlabsClientPart:index}

softnlabs_ticket_part:
    path:    /softnlabsTicket
    defaults: {_controller: AppBundle:SoftnlabsTicketPart:index}

softnlabs_statistique_part:
    path:    /softnlabsStatistique
    defaults: {_controller: AppBundle:SoftnlabsStatistiquePart:index}

login_check:
    path:    /logincheck
    defaults: {_controller: AppBundle:Accueil:EssaiConnexion}

index:
    path:    /connexion
    defaults: {_controller: AppBundle:Default:index}

ticketConsultClient:
    path:    /ticketviewclient/{id}
    defaults: {_controller: AppBundle:TicketViewClient:index}

ticketConsultSNL:
    path:    /ticketviewsnl/{id}
    defaults: {_controller: AppBundle:TicketViewSNL:index}

