app:
    resource: '@AppBundle/Controller/'
    type: annotation

softnlabs:
    path:    /softnlabs
    defaults: {_controller: AppBundle:Softnlabs:index}

client:
    path:    /client
    defaults: {_controller: AppBundle:Client:index}

nouveauTicket:
    path:    /nouveauTicket
    defaults: {_controller: AppBundle:NouveauTicket:index}

softnlabs_client_part:
    path:    /softnlabsClientPartController
    defaults: {_controller: AppBundle:SoftnlabsClientPart:index}

softnlabs_ticket_part:
    path:    /softnlabsTicketPartController
    defaults: {_controller: AppBundle:SoftnlabsTicketPart:index}

softnlabs_statistique_part:
    path:    /softnlabsStatistiquePartController
    defaults: {_controller: AppBundle:SoftnlabsStatistiquePart:index}


login_check:
    path:    /logincheck
    defaults: {_controller: AppBundle:Accueil:EssaiConnexion}
